"""

Revision ID: 2817d9327044
Revises: 8b00548301dc
Create Date: 2025-10-21 20:49:06.519971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2817d9327044'
down_revision: Union[str, None] = '8b00548301dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_keys_user_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('diffs_environment_id_fkey'), 'diffs', type_='foreignkey')
    op.create_foreign_key(None, 'diffs', 'run_time_environments', ['environment_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('organization_memberships_organization_id_fkey'), 'organization_memberships', type_='foreignkey')
    op.drop_constraint(op.f('organization_memberships_user_id_fkey'), 'organization_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'organization_memberships', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'organization_memberships', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('run_time_environments_created_by_fkey'), 'run_time_environments', type_='foreignkey')
    op.create_foreign_key(None, 'run_time_environments', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('test_memberships_test_id_fkey'), 'test_memberships', type_='foreignkey')
    op.drop_constraint(op.f('test_memberships_test_suite_id_fkey'), 'test_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'test_memberships', 'test_suites', ['test_suite_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'test_memberships', 'tests', ['test_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('test_runs_test_suite_id_fkey'), 'test_runs', type_='foreignkey')
    op.drop_constraint(op.f('test_runs_environment_id_fkey'), 'test_runs', type_='foreignkey')
    op.drop_constraint(op.f('test_runs_created_by_fkey'), 'test_runs', type_='foreignkey')
    op.drop_constraint(op.f('test_runs_test_id_fkey'), 'test_runs', type_='foreignkey')
    op.create_foreign_key(None, 'test_runs', 'test_suites', ['test_suite_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'test_runs', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'test_runs', 'run_time_environments', ['environment_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'test_runs', 'tests', ['test_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('test_suites_owner_fkey'), 'test_suites', type_='foreignkey')
    op.create_foreign_key(None, 'test_suites', 'users', ['owner'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_suites', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('test_suites_owner_fkey'), 'test_suites', 'users', ['owner'], ['id'])
    op.drop_constraint(None, 'test_runs', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'test_runs', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'test_runs', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'test_runs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('test_runs_test_id_fkey'), 'test_runs', 'tests', ['test_id'], ['id'])
    op.create_foreign_key(op.f('test_runs_created_by_fkey'), 'test_runs', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('test_runs_environment_id_fkey'), 'test_runs', 'run_time_environments', ['environment_id'], ['id'])
    op.create_foreign_key(op.f('test_runs_test_suite_id_fkey'), 'test_runs', 'test_suites', ['test_suite_id'], ['id'])
    op.drop_constraint(None, 'test_memberships', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'test_memberships', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('test_memberships_test_suite_id_fkey'), 'test_memberships', 'test_suites', ['test_suite_id'], ['id'])
    op.create_foreign_key(op.f('test_memberships_test_id_fkey'), 'test_memberships', 'tests', ['test_id'], ['id'])
    op.drop_constraint(None, 'run_time_environments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('run_time_environments_created_by_fkey'), 'run_time_environments', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'organization_memberships', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'organization_memberships', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('organization_memberships_user_id_fkey'), 'organization_memberships', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('organization_memberships_organization_id_fkey'), 'organization_memberships', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'diffs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('diffs_environment_id_fkey'), 'diffs', 'run_time_environments', ['environment_id'], ['id'])
    op.drop_constraint(None, 'api_keys', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_user_id_fkey'), 'api_keys', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
