# Docker Compose for Matrixes 

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: matrixes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

